development:
  adapter: postgresql
  encoding: unicode
  database: adaptive_coke_dev
  username: pocketed
  password: pocketed

test:
  adapter: postgresql
  encoding: unicode
  database: adaptive_coke_test
  username: pocketed
  password: pocketed
  host: localhost